In [108]:
import numpy as np

In [109]:
np.random.seed(101)
arr = np.random.randint(0,100,10)

In [110]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [111]:
arr.max()

95

In [114]:
arr.argmax()

0

In [115]:
arr.min()

9

In [116]:
arr.argmin()

7

In [117]:
arr.reshape(5,2)

array([[95, 11],
       [81, 70],
       [63, 87],
       [75,  9],
       [77, 40]])

In [120]:
mat = np.arange(0,100).reshape(10,10)

In [121]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [122]:
mat[5,2]

52

In [131]:
mat[3:8,3:7] = 0

In [129]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32,  0,  0,  0,  0, 37, 38, 39],
       [40, 41, 42,  0,  0,  0,  0, 47, 48, 49],
       [50, 51, 52,  0,  0,  0,  0, 57, 58, 59],
       [60, 61, 62,  0,  0,  0,  0, 67, 68, 69],
       [70, 71, 72,  0,  0,  0,  0, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])